const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('assets/app.js','utf8').split("document.addEventListener(")[0];
const ctx=vm.createContext({window:{},localStorage:{removeItem(){}},Intl,Date,URL,console});
vm.runInContext(source,ctx);
const run=s=>vm.runInContext(s,ctx);
assert(run("occursOnDate({weekday:0,frequency:'weekly'},'2026-10-05')"));
assert(!run("occursOnDate({weekday:0,frequency:'weekly'},'2026-10-06')"));
assert(run("occursOnDate({weekday:0,frequency:'biweekly',recurrence_anchor:'2026-10-05'},'2026-10-19')"));
assert(!run("occursOnDate({weekday:0,frequency:'biweekly',recurrence_anchor:'2026-10-05'},'2026-10-12')"));
assert(!run("occursOnDate({weekday:0,excluded_dates:['2026-10-05']},'2026-10-05')"));
assert(!run("occursOnDate({weekday:0,date:'2026-10-05',frequency:'one-time',sources:[{url:'https://comediq.us/mics.json'}]},'2026-10-12')"));
assert.equal(run("scheduleLabel({frequency:'one-time'})"),'Pop-up mic (not recurring)');
assert.equal(run("claimLabel({venue_confirmed:true})"),'Venue confirmed');
assert.equal(run("claimLabel({venue_confirmed:true,claimed:true})"),'Host claimed');
console.log('Date matching, recurrence, exclusions and labels passed');
assert(!run("occursOnDate({weekday:null},'2026-10-05')"));
assert(!run("isBiweekly({frequency:'one-time',notes:'formerly biweekly'})"));
assert(!run("validDate('2026-02-30')"));
assert(run("validDate('2028-02-29')"));
run("state.date=null;state.day=0");
assert(run("occurs({weekday:0,date:'2020-01-06',sources:[{url:'https://comediq.us/mics.json'}]})"));
assert.equal(run("scheduleLabel({weekday:0,date:'2020-01-06',sources:[{url:'https://comediq.us/mics.json'}]})"),'Weekly');
console.log('Regression checks passed');
const irregular="{id:'irregular',name:'Irregular mic',venue:'Venue',borough:'Queens',weekday:0,start_time:'19:00',frequency:'non-weekly',status:'scheduled',notes:'Non-weekly; exact dates unknown.'}";
assert.equal(run(`scheduleLabel(${irregular})`),'Non-weekly · check schedule');
assert(!run(`isBiweekly(${irregular})`));
assert(!run(`occursOnDate(${irregular},'2026-10-05')`));
assert(!run(`occursOnDate(${irregular},'2026-10-12')`));
run("state.date=null;state.day=0");
assert(run(`occurs(${irregular})`));
run("state.day='all'");
assert(run(`occurs(${irregular})`));
assert.equal(run(`scheduleDay(${irregular},true)`),'Monday · dates unconfirmed');
assert(run(`card(${irregular})`).includes('Dates unconfirmed'));
assert(!run(`card(${irregular})`).includes('Dec 31'));
run("state.date='2026-10-05'");
assert(!run(`occurs(${irregular})`));
assert.equal(run(`scheduleDay(${irregular},true)`),'Monday · dates unconfirmed');
assert(run("occursOnDate({weekday:null,date:'2026-10-05',frequency:'non-weekly'},'2026-10-05')"));
assert(!run("occursOnDate({weekday:null,date:'2026-10-05',frequency:'non-weekly'},'2026-10-12')"));
console.log('Non-weekly import visibility and honest date labels passed');

// Actual Comediq import shape: generated date, no stored weekday.
const datedImport={weekday:null,date:'2026-10-06',frequency:'weekly',sources:[{url:'https://comediq.us/mics.json'}]};
ctx.datedImport=datedImport;
assert.equal(run('recurrenceDay(datedImport)'),1);
assert(run("occursOnDate(datedImport,'2026-10-13')"));
assert(!run("occursOnDate(datedImport,'2026-10-12')"));
run("state.date=null;state.day=1");
assert(run('occurs(datedImport)'));
assert.equal(run('weekday(nextDate(datedImport))'),1);
assert.notEqual(run('nextDate(datedImport)'),'9999-12-31');
run('state.day=0');
assert(!run('occurs(datedImport)'));
assert(!run("occursOnDate({...datedImport,frequency:'non-weekly'},'2026-10-13')"));
assert(run("occursOnDate({...datedImport,overridden_fields:['date']},'2026-10-06')"));
assert(!run("occursOnDate({...datedImport,overridden_fields:['date']},'2026-10-13')"));
assert(!run("occursOnDate({...datedImport,frequency:'one-time'},'2026-10-13')"));
assert.equal(run("recurrenceDay({...datedImport,weekday:2})"),2);
assert.equal(run("recurrenceDay({weekday:null,date:'2026-10-06'})"),null);
assert.equal(run("recurrenceDay({...datedImport,date:'2026-02-30'})"),null);
console.log('Comediq dates without weekdays remain searchable; explicit dates stay exact');
